ban-webhook:
  url: ""
  embed-title: "SanctionsSystem - New Ban !"
  embed-content: "{player} has just been banned for {reason} during {time} by {author}."

mute-webhook:
  url: ""
  embed-title: "SanctionsSystem - New Mute !"
  embed-content: "{player} has just been muted for {reason} during {time} by {author}."

kick-webhook:
  url: ""
  embed-title: "SanctionsSystem - New Kick !"
  embed-content: "{player} has just been kicked for {reason} by {author}."

ban-message: "§cYou have been banned from this server !\nReason : {reason}.\nRemaining time : {remaining}.\nAuthor : {author}."
ban-broadcast-message: "§cThe player {player} has just been banned for {reason} during {time} by {author}."
unban-broadcast-message: "§cThe player {player} has just been unbanned by {author}."
already-ban-message: "§cThis player is already banned."
not-ban-message: "§cThis player is not banned."

mute-message: "§cYou have been muted from this server !\nReason : {reason}.\nRemaining time : {remaining}.\nAuthor : {author}."
mute-broadcast-message: "§cThe player {player} has just been muted for {reason} during {time} by {author}."
unmute-broadcast-message: "§cThe player {player} has just been unmuted by {author}."
already-mute-message: "§cThis player is already muted."
not-mute-message: "§cThis player is not muted."

kick-message: "§cYou have been kicked from this server !\nReason : {reason}.\nAuthor : {author}."
kick-broadcast-message: "§cThe player {player} has just been kicked for {reason} by {author}."
not-connected: "§cThis player is not connected."

freeze-message: "§cYou have been freezed by {author}."
self-freeze-message: "§cYou have freeze {player}."
unfreeze-message: "§cYou have been unfreezed by {author}."
self-unfreeze-message: "§cYou have unfreeze {player}."
not-freezed-message: "§cThis player is not freezed."

alias-title: "{player}'s accounts :"
alias-accounts: " - {accounts}."

